### ISSUE TITLE
Inlay hints not working

### ISSUE THREAD

**Issue by Kryszak** [simrat39/rust-tools.nvim#309] opened 2023-01-02 09:25 UTC
After update of rust-tools and Mason rust-analyzer inlay hints stopped working with following error:

```Error executing vim.schedule lua callback: ...ker/start/rust-tools.nvim/lua/rust-tools/inlay_hints.lua:216: bad argument #1 to 'sub' (string expected, got table)
stack traceback:
        [C]: in function 'sub'
        ...ker/start/rust-tools.nvim/lua/rust-tools/inlay_hints.lua:216: in function 'render_line'
        ...ker/start/rust-tools.nvim/lua/rust-tools/inlay_hints.lua:260: in function 'render'
        ...ker/start/rust-tools.nvim/lua/rust-tools/inlay_hints.lua:170: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

```
$ ./rust-analyzer --version
rust-analyzer 0.3.1344-standalone
```

**Comment by augustocdias** [comment] 2023-01-02 09:47
The issue seems to be here as it is passing a table instead of a string:

https://github.com/simrat39/rust-tools.nvim/blob/master/lua/rust-tools/inlay_hints.lua#L216

**Comment by kesleta** [comment] 2023-01-02 10:26
Seems like there's already a pull request to solve it: #308

**Comment by kesleta** [comment] 2023-01-02 10:35
This issue actually seems to be a duplicate of #300.

**Comment by MichaelMandel26** [comment] 2023-01-02 11:11
There are multiple PRs for this: https://github.com/simrat39/rust-tools.nvim/pull/307 and https://github.com/simrat39/rust-tools.nvim/pull/308

**Comment by Firaenix** [comment] 2023-01-04 02:49
Same thing actually happens when opening the floating preview window too if you want to use the debugging feature

```
E5108: Error executing lua ...lar/neovim/0.8.1/share/nvim/runtime/lua/vim/lsp/util.lua:1525: contents: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        ...lar/neovim/0.8.1/share/nvim/runtime/lua/vim/lsp/util.lua:1525: in function 'open_floating_preview'
        [string ":lua"]:1: in main chunk
```

**Comment by krolyxon** [comment] 2023-01-04 07:42
guys i dont think simrat39 is going to merge the pr any time soon, so just merge the pr into your own fork for now.

**Comment by ostap-tymchenko** [comment] 2023-01-04 13:58
(for those who dont want to fork just use a pr's fork like https://github.com/kdarkhan/rust-tools.nvim temporary)

**Comment by calops** [comment] 2023-01-05 21:46
That fork has the exact same issue for me.

**Comment by kesleta** [comment] 2023-01-07 16:34
Is there any reason why it's not getting merged? Is this repo just not being maintained very much currently?

**Comment by anstadnik** [comment] 2023-01-07 17:08
I guess there is just an avalanche of issues, and @simrat39 cannot handle all of them instantly.

**Comment by simrat39** [comment] 2023-01-08 00:20
Fixed in https://github.com/simrat39/rust-tools.nvim/commit/a47f5d61ce06a433998fb5711f723773e3156f46

**Closed by simrat39** 2023-01-08 00:20 UTC

**Comment by ostap-tymchenko** [comment] 2023-01-09 11:26
For everyone that temporeraly switched to a fork double check that you've switched back to main!
