### ISSUE TITLE
Debug after codelldb updates doesnt work

### ISSUE THREAD

**Issue by martinsrso** [simrat39/rust-tools.nvim#157] opened 2022-03-20 01:53 UTC
After I update codelldb provide by vscode to version `1.70` my debugger configured using rust-tools stopped working as the error below.
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/11994788/159144622-0f0b1946-b1e2-48ce-b77f-9e533d0a339e.png">

**Comment by test210820** [comment] 2022-03-21 15:36
same problem

**Comment by rgnkn** [comment] 2022-03-24 07:19
Same

**Comment by glindstedt** [comment] 2022-03-30 21:44
It seems like the relevant changes are in this commit: https://github.com/vadimcn/vscode-lldb/commit/08dcebab314acd3ab275e6af23c8b867e6548135

Looks like a refactor so that the adapter would be able to reverse connect to a port exposed by the extension by using the `--connect` flag. Previously there was only the `--port` flag which defaulted to 0 (which means pick any random port). However it seems like there's a regression because previously codelldb would print `Listening on port xyz` on startup but in the new version nothing is printed, and it also doesn't respond to Ctrl-C (which 1.6.10 does).

**Comment by simrat39** [comment] 2022-03-31 05:24
hmm I think a good workaround (for now) would be either giving a port in the config, or trying to find an empty port (not too sure about a cross platform implementation for the latter option)

**Comment by Freyskeyd** [comment] 2022-04-07 15:48
I tried to update the configuration to allow `port` or `connect` but it seems to hang for ever...
I tried to check what vscode is doing when starting a debugging session but it's not really helpful.

I would like to help on this issue but I don't know where to start...

**Comment by simrat39** [comment] 2022-04-07 20:51
> I tried to update the configuration to allow `port` or `connect` but it seems to hang for ever... I tried to check what vscode is doing when starting a debugging session but it's not really helpful.
> 
> I would like to help on this issue but I don't know where to start...

You are probably not passing the port to dap if I had to guess

**Comment by tpoliaw** [comment] 2022-04-07 22:24
How do you pass the port to dap?

**Comment by Freyskeyd** [comment] 2022-04-08 14:14
> hmm I think a good workaround (for now) would be either giving a port in the config, or trying to find an empty port (not too sure about a cross platform implementation for the latter option)

How do you think we need to tackle this subject ?
Do we provide a way to define a range of port in config so that the adapter randomly take one without checking if it's free to be used ? This solution is much simpler but some failure can happened if the address is already in used.

The other solution seems more complicated because of the platform dependency to check for a free port. Do we have any way to do that for now?

**Comment by simrat39** [comment] 2022-04-08 14:26
> > hmm I think a good workaround (for now) would be either giving a port in the config, or trying to find an empty port (not too sure about a cross platform implementation for the latter option)
> 
> How do you think we need to tackle this subject ?
> Do we provide a way to define a range of port in config so that the adapter randomly take one without checking if it's free to be used ? This solution is much simpler but some failure can happened if the address is already in used.
> 
> The other solution seems more complicated because of the platform dependency to check for a free port. Do we have any way to do that for now?

I have a working implementation in libuv, if we bind to port 0 then the os automatically reassigns a free port to us. I have it tested on Linux and I'm pretty sure windows does the same thing but not too sure about MacOS

**Comment by Freyskeyd** [comment] 2022-04-08 14:27
@simrat39 I can confirm that passing a `port 0` is ok for OSX too.

How do you fetch the generated port tho?

**Comment by simrat39** [comment] 2022-04-08 14:32
> @simrat39 I can confirm that passing a `port 0` is ok for OSX too.
> 
> How do you fetch the generated port tho?

```lua
local loop = vim.loop

local server = loop.new_tcp()

P(loop.tcp_bind(server, "127.1.0.0", 0))

P(server.getsockname(server).port)

```

(P is just a print function in my config)

**Comment by Freyskeyd** [comment] 2022-04-08 14:54
Nice ! I can't wait to see the rest of the implementation :)

**Comment by simrat39** [comment] 2022-04-09 02:17
```
diff --git a/lua/rust-tools/dap.lua b/lua/rust-tools/dap.lua
index 8ed0fec..8a37ef4 100644
--- a/lua/rust-tools/dap.lua
+++ b/lua/rust-tools/dap.lua
@@ -1,22 +1,35 @@
 local config = require("rust-tools.config")
+local loop = vim.loop
 
 local M = {}
 
+local function get_free_port()
+  local server = loop.new_tcp()
+  server:bind("127.0.0.1", 0)
+  return server:getsockname().port
+end
+
+P(get_free_port())
+
 ---For the heroes who want to use it
 ---@param codelldb_path string
 ---@param liblldb_path string
-function M.get_codelldb_adapter(codelldb_path, liblldb_path)
+---@param port number to pass to codelldb
+function M.get_codelldb_adapter(codelldb_path, liblldb_path, port)
   return function(callback, _)
     local stdout = vim.loop.new_pipe(false)
     local stderr = vim.loop.new_pipe(false)
     local handle
     local pid_or_err
-    local port
     local error_message = ""
 
+    port = port or get_free_port()
+
+    P(port)
+
     local opts = {
       stdio = { nil, stdout, stderr },
-      args = { "--liblldb", liblldb_path },
+      args = { "--liblldb", liblldb_path, "--port", port },
       detached = true,
     }
 
@@ -35,24 +48,9 @@ function M.get_codelldb_adapter(codelldb_path, liblldb_path)
     stdout:read_start(function(err, chunk)
       assert(not err, err)
       if chunk then
-        if not port then
-          local chunks = {}
-          for substring in chunk:gmatch("%S+") do
-            table.insert(chunks, substring)
-          end
-          port = tonumber(chunks[#chunks])
-          vim.schedule(function()
-            callback({
-              type = "server",
-              host = "127.0.0.1",
-              port = port,
-            })
-          end)
-        else
-          vim.schedule(function()
-            require("dap.repl").append(chunk)
-          end)
-        end
+        vim.schedule(function()
+          require("dap.repl").append(chunk)
+        end)
       end
     end)
     stderr:read_start(function(_, chunk)
@@ -64,6 +62,14 @@ function M.get_codelldb_adapter(codelldb_path, liblldb_path)
         end)
       end
     end)
+
+    vim.schedule(function()
+      callback({
+        type = "server",
+        host = "127.0.0.1",
+        port = port,
+      })
+    end)
   end
 end
 

```

Looks like debugging works with this but we need to run it twice, dap is unable to connect first try, not sure why

**Comment by Freyskeyd** [comment] 2022-04-09 09:50
@simrat39 Oh yes, it's because of a concurrency issue.

you can wrap:

```

vim.defer_fn(function()
	vim.schedule(function()
		callback({
			type = "server",
			host = "127.0.0.1",
			port = port,
		})
	end)
end, 100)
```

I don't know about the TTL but we can't have something listening (or polling) to the process to start listen on the given port.

**Comment by aniketfuryrocks** [comment] 2022-04-30 10:25
The plugin didn't throw any error in my case and just web silent.
Please pin this issue or mention that debugger after version `1.6.10` is `WIP`.
Spent a whole day debugging this plugin.

**Comment by dialtone** [comment] 2022-06-30 02:28
Just chiming in here that gigablaster's patch actually works for me as well.

**Comment by simrat39** [comment] 2022-07-19 00:08
Should be fixed in the https://github.com/simrat39/rust-tools.nvim/tree/modularize_and_inlay_rewrite branch

**Comment by alejandroreyesj** [comment] 2022-08-05 02:08
Has anyone figured out how to fix this? I have this config:

```

if server == "rust_analyzer" then
     local keymap = vim.keymap.set
     local key_opts = { silent = true }
     **local extension_path = vim.env.HOME .. '/.vscode/extensions/vadimcn.vscode-lldb-1.7.3/'
     local codelldb_path = extension_path .. 'adapter/codelldb'
     local liblldb_path = extension_path .. 'lldb/lib/liblldb.so'**

     keymap("n", "<leader>rh", "<cmd>RustSetInlayHints<Cr>", key_opts)
     keymap("n", "<leader>rhd", "<cmd>RustDisableInlayHints<Cr>", key_opts)
     keymap("n", "<leader>th", "<cmd>RustToggleInlayHints<Cr>", key_opts)
     keymap("n", "<leader>rr", "<cmd>RustRunnables<Cr>", key_opts)
     keymap("n", "<leader>rem", "<cmd>RustExpandMacro<Cr>", key_opts)
     keymap("n", "<leader>roc", "<cmd>RustOpenCargo<Cr>", key_opts)
     keymap("n", "<leader>rpm", "<cmd>RustParentModule<Cr>", key_opts)
     keymap("n", "<leader>rjl", "<cmd>RustJoinLines<Cr>", key_opts)
     keymap("n", "<leader>rha", "<cmd>RustHoverActions<Cr>", key_opts)
     keymap("n", "<leader>rhr", "<cmd>RustHoverRange<Cr>", key_opts)
     keymap("n", "<leader>rmd", "<cmd>RustMoveItemDown<Cr>", key_opts)
     keymap("n", "<leader>rmu", "<cmd>RustMoveItemUp<Cr>", key_opts)
     keymap("n", "<leader>rsb", "<cmd>RustStartStandaloneServerForBuffer<Cr>", key_opts)
     keymap("n", "<leader>rd", "<cmd>RustDebuggables<Cr>", key_opts)
     keymap("n", "<leader>rv", "<cmd>RustViewCrateGraph<Cr>", key_opts)
     keymap("n", "<leader>rw", "<cmd>RustReloadWorkspace<Cr>", key_opts)
     keymap("n", "<leader>rss", "<cmd>RustSSR<Cr>", key_opts)
     keymap("n", "<leader>rxd", "<cmd>RustOpenExternalDocs<Cr>", key_opts)

    require("rust-tools").setup {
       tools = {
         on_initialized = function()
           vim.cmd [[
             autocmd BufEnter,CursorHold,InsertLeave,BufWritePost *.rs silent! lua vim.lsp.codelens.refresh()
           ]]
         end,
       },
       **dap = {adapter = require('rust-tools.dap').get_codelldb_adapter(
            codelldb_path, liblldb_path)},**
      server = {
        on_attach = require("user.lsp.handlers").on_attach,
        capabilities = require("user.lsp.handlers").capabilities,
         settings = {
           ["rust-analyzer"] = {
             lens = {
               enable = true,
             },
             cargo = {
              buildScripts = {
                  enable = true,
              },
              },
              procMacro = {
                  enable = true
              },
            checkOnSave = {
               command = "clippy",
             },
           },
         },
       },
    }

```


 I'm getting `Error: "Either --connect or --port must be specified"` with vscode-lldb-1.7.3

**Comment by augustocdias** [comment] 2022-08-05 07:56
> Has anyone figured out how to fix this? I have this config:
> I'm getting `Error: "Either --connect or --port must be specified"` with vscode-lldb-1.7.3

https://github.com/simrat39/rust-tools.nvim/issues/157#issuecomment-1188455733

**Closed** 2022-08-08 23:38 UTC

**Comment by Xoffio** [comment] 2023-04-26 03:59
Hi guys! I am using AstroNvim and I am having the same issue

this is part of my `init.lua`
```lua
rust_analyzer = function(_, opts)
        local extension_path = vim.env.HOME .. '/.vscode/extensions/vadimcn.vscode-lldb-1.9.0/'
        local codelldb_path = extension_path .. 'adapter/codelldb.exe'
        local liblldb_path = extension_path .. 'lldb/lib/liblldb.lib' -- MacOS: This may be .dylib

        require("rust-tools").setup {
          server = opts,
          dap = {
            adapter = require('rust-tools.dap').get_codelldb_adapter(codelldb_path, liblldb_path)
          }
        }
      end
```

This is the error:
![dap_error_01](https://user-images.githubusercontent.com/38369407/234466180-4127d3c0-9096-4344-8150-99587ba525ee.jpg)

> Should be fixed in the https://github.com/simrat39/rust-tools.nvim/tree/modularize_and_inlay_rewrite branch

So for me to fix this I have to use this branch? how can I tell nvim to get the code from that specific branch? Thanks!

**Comment by utkarshgupta137** [comment] 2023-04-26 17:27
With AstroNvim, you could just use the community rust pack: https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/pack/rust.

**Comment by Xoffio** [comment] 2023-04-27 04:08
@utkarshgupta137  Thank you for the info! I didn't know that package existed. Unfortunately it didn't work either... I created an [issue](https://github.com/AstroNvim/astrocommunity/issues/167). I am getting the same error i was describing before...
