### ISSUE TITLE
Inlay hints not showing up

### ISSUE THREAD

**Issue by ccarral** [simrat39/rust-tools.nvim#197] opened 2022-05-13 03:14 UTC
My inlay hints stopped working for a while now and I don't know why, as all other `rust-tools` commands and lsp features seem to work fine. `:RustSetInlayHints` doesn't seem to do anything. Neither does calling `:lua require('rust-tools.inlay_hints').set_inlay_hints()` directly.
For the record, I use `nvim-lsp-installer` with the config inspired by #89 . Here is my config:

```lua
local global_opts = {
        on_attach = on_attach,
        settings = {
            ["rust-analyzer"] = {
                completion = {
                    postfix = {
                        enable = false
                    }
                },
                checkOnSave = {
                    command = "clippy"
                },
            }
        }
} 

local rust_opts = {
    tools = { 
        -- rust-tools options
        autoSetHints = true,
        hover_with_actions = true,
        inlay_hints = {
            only_current_line = false,
            show_parameter_hints = true,
        },
    },
    server = global_opts,
}


local lsp_installer = require("nvim-lsp-installer")

lsp_installer.on_server_ready(function(server)
    if server.name == "rust_analyzer" then
        local server_options = server:get_default_options()
        server_options['on_attach'] = on_attach
        rust_opts.server = vim.tbl_deep_extend("force",server_options, global_opts) 
        require('rust-tools').setup(rust_opts)
        server:attach_buffers()
   elseif server.name == "volar" then
          local volar_options = server:get_default_options()
          volar_options["cmd"] = {"vls","--stdio"}
          volar_options["on_attach"] = on_attach
          volar_options["init_options"] = {
              serverPath = "~/.npm/lib/node_modules/typescript/lib/tsserver.js"
          }
          server:setup(volar_options)
   else
       server:setup(global_opts)
   end
end)

``` 

neovim version: v0.8.0-dev+150-g6c39f9d42 (nightly)

**Comment by AjiBuster499** [comment] 2022-05-13 12:49
nvim-lsp-installer recently adjusted their setup call, so it no longer calls lspconfig's setup for you, instead you just call lsp-installer's setup function first, then start lsp servers with lspconfig like normal (or with rust-tools in this case)

**Comment by AjiBuster499** [comment] 2022-05-13 14:08
[Right here on nvim-lsp-installer's README](https://github.com/williamboman/nvim-lsp-installer#usage)
``require("nvim-lsp-installer").setup {}``
After calling this method you can just setup servers as you would normally.

**Comment by ccarral** [comment] 2022-05-13 18:58
I updated my config, still no change
```lua
require("nvim-lsp-installer").setup()
require("lspconfig")

local servers = {'sumneko_lua', 'tsserver', 'pyright', 'clangd', 'rust_analyzer', 'volar', 'jdtls'}

for _,lsp in pairs(servers) do
    if lsp == "rust_analyzer" then
        require('rust-tools').setup(rust_opts)
   elseif lsp == "volar" then
          local volar_options = vim.deepcopy(global_opts)
          volar_options["cmd"] = {"vls","--stdio"}
          volar_options["init_options"] = {
              serverPath = "~/.npm/lib/node_modules/typescript/lib/tsserver.js"
          }
          require("lspconfig")[lsp].setup(volar_options)
   else
          require("lspconfig")[lsp].setup(global_opts)
   end
end
```

**Comment by 5cat** [comment] 2022-05-14 00:10
Anything after this commit [e29fb47326093fb197f17eae5ac689979a9ce191](https://github.com/simrat39/rust-tools.nvim/tree/e29fb47326093fb197f17eae5ac689979a9ce191) did not work for me.
This [commit](https://github.com/simrat39/rust-tools.nvim/commit/87c7dde02642e520192791b2357b45f5879fb5c1) seems to be the cause.
This seems to solve it.
```vim
Plug 'simrat39/rust-tools.nvim', { 'commit': 'e29fb47326093fb197f17eae5ac689979a9ce191' }
```
I wish there is a stable branch or version tags that I can rely on, idk im new to this whole vim plug in thing.

**Comment by abayomi185** [comment] 2022-05-15 21:37
I had this issue as well but updated `rust-analyzer` with `LspInstall` and it works again.

**Comment by sabitm** [comment] 2022-05-16 09:26
> I had this issue as well but updated `rust-analyzer` with `LspInstall` and it works again.

Confirmed. Updating `rust-analyzer` works for me (without changing anything)

**Comment by ephoris** [comment] 2022-05-22 07:27
I am also having the same problems. I was snooping around, it looks like the nvim-lsp-installer creator used to haev a page specifically for rust, but unfortunately they removed the wiki page (https://github.com/williamboman/nvim-lsp-installer/wiki/Rust)

For reference, I think this is the correct way to do things now with the nvim-lsp-installer, but again it produces in inlay_hints even with the latest rust-analyzer installed.

```lua
require('packer').startup(function(use)
    use 'simrat39/rust-tools.nvim'
    use 'neovim/nvim-lspconfig'
    use 'williamboman/nvim-lsp-installer'
end)

require('nvim-lsp-installer').setup({})

local rust_opts = {
    tools = {
        autoSetHints = true,
        inlay_hints = {
            only_current_line = false,
            show_parameter_hints = true,
        }
    },
}

for _, server in ipairs(require('nvim-lsp-installer').get_installed_servers())
do
    if server == 'rust_analyzer' then
        require('rust-tools').setup(rust_opts)
    else
        require('lspconfig')[server.name].setup({})
    end
end
```

**Comment by nkhlmn** [comment] 2022-05-29 21:22
I was having the same issue eventually got it inlay hints working by using the config @ephoris posted. However, now my lsp keymaps are getting wiped for rust files. I have these set in the `on_attach` method being passed to lspconfig's setup function. Anyone have any idea of why?

**Comment by mlthlschr** [comment] 2022-06-25 20:11
@nkhlmn solution worked for me. `require('rust-tools').setup(...)` behind lsp's setup(), passing `on_attach` and `capabilities`.

**Comment by simrat39** [comment] 2022-07-14 00:51
> @nkhlmn solution worked for me. `require('rust-tools').setup(...)` behind lsp's setup(), passing `on_attach` and `capabilities`.

Please don't call lspconfig's setup as rust tools does it already

**Comment by simrat39** [comment] 2022-07-14 00:52
Closing since fixed

**Closed by simrat39** 2022-07-14 00:52 UTC
